---
development: 
  cloud_name: "tiagopinto"
  api_key: "557796252682857"
  api_secret: "COzib19YGEqkusNLw3roc19-Nik"
  secure: true
production:
  cloud_name: "tiagopinto"
  api_key: "557796252682857"
  api_secret: "COzib19YGEqkusNLw3roc19-Nik"
  secure: true
test:
  cloud_name: "tiagopinto"
  api_key: "557796252682857"
  api_secret: "COzib19YGEqkusNLw3roc19-Nik"
  secure: true